Repository eliashaeussler/typo3-sitemap-robots, pull requests merged in 2025-03, with the labels that each got.

#67 [BUGFIX] Ignore site language when enhancing robots.txt with sitemap
  Classes/Middleware/RobotsTxtSitemapHandler.php
  Classes/Resource/RobotsTxtEnhancer.php
  Tests/Functional/Middleware/RobotsTxtSitemapHandlerTest.php
  Tests/Functional/Resource/RobotsTxtEnhancerTest.php
Labels: bug

#68 [!!!][TASK] Drop support for TYPO3 v11
  .github/workflows/tests.yaml
  Classes/DependencyInjection/ReducedSitemapProviderPass.php
  Classes/Exception/UnsupportedServiceRequested.php
  Configuration/Services.php
  Configuration/Services.yaml
  Configuration/SiteConfiguration/Overrides/site.php
  Documentation/Installation/Index.rst
  Documentation/Introduction/Index.rst
  README.md
  Tests/CGL/phpstan-baseline.neon
  Tests/CGL/rector.php
  Tests/Functional/Middleware/RobotsTxtSitemapHandlerTest.php
  Tests/Functional/Resource/RobotsTxtEnhancerTest.php
  Tests/Functional/SiteTrait.php
  Tests/Unit/DependencyInjection/ReducedSitemapProviderPassTest.php
  Tests/Unit/Exception/FileDoesNotExistTest.php
  Tests/Unit/Exception/UnsupportedServiceRequestedTest.php
  Tests/Unit/Resource/RobotsTxtFactoryTest.php
  composer.json
  composer.lock
  ext_emconf.php
Labels: breaking, maintenance

#65 [feat] add option to inject sitemap language versions into robots.txt
  Classes/Enum/EnhancementStrategy.php
  Classes/Middleware/RobotsTxtSitemapHandler.php
  Classes/Resource/RobotsTxtEnhancer.php
  Classes/Updates/LegacySiteConfigurationParameterUpgradeWizard.php
  Configuration/SiteConfiguration/Overrides/site.php
  Documentation/Configuration/Index.rst
  Documentation/Images/site-configuration.png
  Documentation/Index.rst
  Documentation/Migration/Index.rst
  Resources/Private/Language/locallang_db.xlf
  Tests/CGL/dependency-checker.json
  Tests/CGL/phpstan-baseline.neon
  Tests/Functional/Middleware/RobotsTxtSitemapHandlerTest.php
  Tests/Functional/Resource/RobotsTxtEnhancerTest.php
  Tests/Functional/SiteTrait.php
  Tests/Functional/Updates/LegacySiteConfigurationParameterUpgradeWizardTest.php
  Tests/Unit/Enum/EnhancementStrategyTest.php
  composer.json
  composer.lock
Labels: enhancement
